inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "*.gemspec"
    - "spec/**/*"
    - "Rakefile"
    - "yard/**/*"
    - "website/**/*"
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 30
Style/Documentation:
  Enabled: false
