branches:
  only:
    - master
    - travis
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby
  - ree
script: "bundle exec rake spec:normal"
jdk: openjdk7
notifications:
  email:
    recipients:
      - bobaman@google.com
      - sbazyl@google.com
    on_success: change
    on_failure: change
matrix:
  allow_failures:
    - rvm: 2.0.0
