language: ruby
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
  - 2.2.10
  - 2.1.10
  - 2.0.0
  - 1.9.3
  - jruby-9.1.9.0
script: "rake spec:all"
before_install:
 - sudo apt-get update
 - sudo apt-get install idn
 - gem install bundler
notifications:
  email:
    recipients:
      - sbazyl@google.com
      - dazuma@google.com
    on_success: change
    on_failure: change
