name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  CI:
    if: ${{ github.repository == 'googleapis/signet' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "2.5"
            task: spec
          - os: ubuntu-latest
            ruby: "2.6"
            task: spec
          - os: ubuntu-latest
            ruby: "2.7"
            task: spec
          - os: ubuntu-latest
            ruby: "3.0"
            task: spec
          - os: macos-latest
            ruby: "2.7"
            task: spec
          - os: windows-latest
            ruby: "2.7"
            task: spec
          - os: ubuntu-latest
            ruby: "2.7"
            task: rubocop , build , yardoc
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install dependencies
      shell: bash
      run: "gem install --no-document toys && bundle install"
    - name: Test ${{ matrix.task }}
      shell: bash
      run: toys do ${{ matrix.task }} < /dev/null
